### ISSUE TITLE
datdot-css-style-system

### ISSUE THREAD

**Issue by serapath** [datdotorg/datdot-ui#118]
## `@todo`
* [x] support all uses cases and define how to deal with css/styles/themes in apps, components and widgets
    * [x] support default theme values
    * [x] to support user defined themes
    * [x] to support theme updates during "runtime" while the user is interacting with the website
    * [x] to support different component variants (e.g. btn-small, btn-large, ...)
    * [x] to support having differently themed variants of a component inside the same app in parallel
    * [x] to support responsive component instances (with certain variants and themes)
    * [x] to make it easy for developers to understand where to find all the css styles related data and code
    * [x] to make it easy to change and update css styles in the future

---

@fionataeyang if i forgot use cases or you think we should add other kinds of requirements, please add that :-)

**Comment by serapath** [comment]
# example project code to solve all use cases above
The goal is not to make an example app that makes sense in terms of design or content, but instead the goal is to make the most minimalistic "proof of concept" example to cover all issues and uses cases a **css style system** needs to solve and support.


* `index.html`
```html
<!doctype html>
<html>
  <head><meta charset="utf-8"></head>
  <body><script src="demo.js"></script></body>
</html>
```
* `theme.json`
```js
// @TODO: discuss what to add here
{
  "--primary-color": "blue",
  "--primary-font": "arial",
}
```
* `demo.js`
```js
const theme = require('./theme.json')
const app = require('./app.js')

const opts = { }
const el = app(opts)
document.body.append(el)
```
* `app.js`
```js
const bel = require('bel')
const csjs = require('csjs-inject')
module.exports = function app (opts) {
  const el = bel`<div class=${css.app}> hello world </div>
  return el
}
const css = csjs`
.app {
  background-color: green;
}`
```

**Comment by fionataeyang** [comment]
> # example project code to solve all use cases above
> The goal is not to make an example app that makes sense in terms of design or content, but instead the goal is to make the most minimalistic "proof of concept" example to cover all issues and uses cases a **css style system** needs to solve and support.
> 
> * `index.html`
> 
> ```
> <!doctype html>
> <html>
>   <head><meta charset="utf-8"></head>
>   <body><script src="demo.js"></script></body>
> </html>
> ```
> 
> * `theme.json`
> 
> ```js
> // @TODO: discuss what to add here
> {
>   "--primary-color": "blue",
>   "--primary-font": "arial",
> }
> ```
> 
> * `demo.js`
> 
> ```js
> const theme = require('./theme.json')
> const app = require('./app.js')
> // @TODO: discuss what to add here
> const opts = { }
> const el = app(opts)
> document.body.append(el)
> ```
> 
> * `app.js`
> 
> ```js
> const bel = require('bel')
> const csjs = require('csjs-inject')
> const btn = require('./button.js')
> // @TODO: discuss what to add here
> module.exports = function app (opts) {
>   const buttons = [btn('hello world'), btn('hello datdot')]
>   const el = bel`<div class=${css.app}>
>     <h1> example app </h1>
>     ${buttons}
>   </div>
>   return el
> }
> const css = csjs`
> .app {
>   background-color: green;
> }`
> ```
> 
> * `button.js`
> 
> ```js
> const bel = require('bel')
> const csjs = require('csjs-inject')
> // @TODO: discuss what to add here
> module.exports = function button (opts) {
>   const el = bel`<button class=${css.btn}>${text}</button>
>   el.onclick = event => console.log({ text })
>   return el
> }
> const css = csjs`
> .btn {
>   background-color: gray;
> }`
>
