### ISSUE TITLE
cleanup / restructuring (after Fiona)

### ISSUE THREAD

**Issue by ninabreznik** [datdotorg/datdot-ui#123]
## `@todo`

* [x] #119
* [x] cleanup datdot-ui repo
    * [x] move `design/` folder into `datdotorg/assets` repo
    * [x] make all `src/node_modules/*` components into ui repositories under `datdotorg`
      * [x] timeline-days component repo
        * https://github.com/datdotorg/datdot-ui-timeline-days 
      * [x]  tab component repo- has already been done by FIona
        * https://github.com/datdotorg/datdot-ui-tab/blob/main/src/index.js  
      * [x] datepicker component repo
        * https://github.com/datdotorg/datdot-ui-datepicker  
    * [x] merge all changes from https://github.com/datdotorg/datdot-ui into this repositoriy and delete datdot-ui on datdotorg
    * [x] update info section (= below separator line)
* [x] cleanup issues and todos - for more details [see comment below](https://github.com/playproject-io/datdot-ui/issues/123#issuecomment-1079787675)
  * [x] **make cleanup issue**
  * [x] **make styleguide issue**
  * [x] **structure issues and subissues into components + phases issues (1/3)**
  * [x] **structure issues and subissues into components + phases issues (2/3)**
  * [x] **add fix image links todo to cleanup issues**
  * [x] **structure issues and subissues into components + phases issues (3/3)**
  * [x] **don't forget to make an "app component" issue** https://github.com/playproject-io/datdot-ui/issues/169
  * [x] **make a theme issue - maybe linked under the styleguide issue** #170
* [x] cleanup datdot-ui issues
  * [x] sort through all issues and link them properly and fix typos or formatting and make yourself familiar
  * [x] make a structure for each issue (to mark phases & todos for each phase)
  * [x] take care that each issue in this repo has somewhere between `1- 30` todos in its todo list
     * [x] if an issue has more than ~30 todos in its todo list try to group them and make a new issue to move some todos there
     * [x] link the new issue into the old issue where it replaces all the moved todos
* [x] copy over Fiona's notes to the issues https://github.com/playproject-io/datdot-ui/issues/119
---
## organisational restructuring
```
playproject-io ORG
- playproject.github.io (e.g. https://playproject.io)
- * REPOs (e.g. roadmapping REPO)
- datdotorg REPO => datdotorg ORG

datdotorg ORG
- datdotorg.github.io (e.g. https://datdot.org)
- datdot-* REPOs (e.g. datdot-service REPO)
- datdot-ui REPO => datdot-ui ORG

datdot-ui ORG
- datdot-ui-github.io (e.g. design system)
- datdot-ui-* REPOs (e.g. datdot-ui-button)
```

**Comment by serapath** [comment]
**feedback `2022.03.24`**

nice :-)

and :+1: for naming datdotorg datdot-ui in the title. thats cool

### Table of Content [ToC]
while doing this, maybe check issue "info sections" if things can be moved to the correct issues
  * sub components should not link or describe the overall structure, thats for parent issues

**for details see [todo list](https://github.com/playproject-io/datdot-ui/issues/123)

---
**make cleanup issue**

1. i think maybe we can make an issue `"take over and clean up work from fiona"` and all the `"cleanup"` tasks go under it and we link that in the main issue and mark it done once its done.
also the: **"screenshots to make red circles with numbers around visual elements"** task might go there, which means "issue number" about the component represented in the component in the wireframes encircled in red  and that screenshot could go into the info section of the main issue as an overview of which component goes where visually?

---
**make styleguide issue**

2. i would make a style guide issue which includes thinking about the theme selector component and styles and themes how it all works

---
**structure issues and subissues into components + phases issues (1/3)**

3. i would probably make another issue for **"components"** for a list of components instead of using the main datdot-ui issue? ...also the "screen" issues are also technically components for a screen, so maybe they could go there too? ...but yeah i wonder if the root issue should be our "all components" issue or maybe rather not even if that means the root issue has only a single "components" issue ..but at least that should be SEPERATE from a "wireframes" issue, which are not part of the implemented components

---
**structure issues and subissues into components + phases issues (2/3)**

**actually:**
regarding (3.) and checking the "SCREENS" issue where you have a part called "design" and a part called "implement" is a **PERFECT EXAMPLE** of the latest rule we just made in the discord channel.

**every single bullet and sub-bullet point is an issue**

So: instead of how it is now, it probably rather should be:
* datdot-ui#1
  * design-phase
    * wireframe-datdot-webapp
      * wireframe-user-screen
      * wireframe-plan-screen
      * wireframe-work-screen
      * wireframe-apps-screen
      * wireframe-actionbar
      * wireframe-main-notifcation-viewer-overlay
  * implementation-phase
    * implement-datdot-webapp
      * implement-user-screen
      * implement-plan-screen
      * implement-work-screen
      * implement-apps-screen
      * implement-actionbar
      * implement-main-notifcation-viewer-overlay
  * test-phase
    * test-datdot-webapp
      * test-user-screen
      * test-plan-screen
      * test-work-screen
      * test-apps-screen
      * test-actionbar
      * test-main-notifcation-viewer-overlay
  * components
    * component-datdot-webapp
      * wireframe-datdot-webapp
      * implement-datdot-webapp
      * test-datdot-webapp
      * sub-component-user-screen
        * implement-user-screen
        * wireframe-user-screen
        * test-user-screen
        * sub-component-1
        * sub-component-2
        * sub-component-3
      * sub-component-plan-screen
        * implement-plan-screen
        * wireframe-plan-screen
        * test-plan-screen
        * sub-component-1
        * sub-component-2
        * sub-component-3
      * sub-component-work-screen
        * implement-work-screen
        * wireframe-work-screen
        * test-work-screen
        * sub-component-1
        * sub-component-2
        * sub-component-3
      * sub-component-apps-screen
        * implement-apps-screen
        * wireframe-apps-screen
        * test-apps-screen
        * sub-component-1
        * sub-component-2
        * sub-component-3
      * sub-component-actionbar
        * ...
        * ...
      * sub-component-main-notifcation-viewer-overlay
        * ...
        * ...
    
and so on ... that way we can have "phases" and mark things as done and move to the next phase for each components, but we also have a generaly overview of components and what needs to be done to each to finish

---
**add fix image links todo to cleanup issues**

4. just randomly saw on https://github.com/playproject-io/datdot-ui/issues/24 that the screenshot links in the comments are broken, oh and quickly checked, seems to be the case for plan screen and others too, but you mention that in the worklog video :-) maybe thats the case on more other issues too, that should be added as a **TASK: fix broken image links** to the cleanup issue.

anyway, just to make sure that it exists as an issue to fix things, so we dont forget :-)


---
**structure issues and subissues into components + phases issues (3/3)**

5. the `screen plan issue` looks long and of course splitting it into issues for implementation and wireframe design helps, but still, the `data card`, `nav/action bar`, etc... marked ad **bold todos** could be more sub issues again structured like shown above into "implementation" and "design" phase :-)

---
**make a "create overview" issue for table of contents + picture of everything**

6. `"List of UI components" issue` has some todos related to **testing** and i would say that deserves its own issues and maybe it even deserves its own "phase" (which of course we can always work on things in "parallel", that is true, but still, similar to "design" and "implementation" i think this should have a testing issues where we systematically cover everything and that also means another test sub todo for each component to also test it :-)

Also the above mentioned "screenshot(s)" with red encircled areas + issue number could go here into the issues info section, so we have a little visual cue which component issue in the list is about what part in the UI :-)  i guess this can be taken from fionas wireframe to make screenshots of some views that show the relevant stuff so we capture all components and break down the wireframes into a modular component system  ...maybe inside of each component issue all the different states (expanded/collapsed/etc...) can be shown in more detail to not overwhelm the top level issue

:+1: to updating the component list


---
**don't forget to make an "app component" issue**

7. "App preview" in a way that is just yet another component with a preview.
In this case its the entire app which has the 4 screens as sub components, so we could technically treat it just like the others and maybe take those two repos (template and webapp/electron) and make them todos and maybe assign me, so i will work on them and rename and stuff when i know exactly how that should be structured ... will anyway take some time to finish all the rest before this becomes urgent

---
**make a theme issue - maybe linked under the styleguide issue**

8. "theme inspiration" issue, so maybe we can also have an issue where we collect different inspirations for different themes. fiona made some funky themes initially but we can have a place to collect more ideas for when we get to making themes :-)

**Comment by serapath** [comment]
**feedback `2022.03.26`**

yeah, progress looks good, and also your plans sound great. cool :-)

**a few remarks:**
* I feel the "info section" in issue [`plan screen` issue](https://github.com/playproject-io/datdot-ui/issues/22) needs some changing too and not all of it does belong to that issue
* in the [`user screen` issue](https://github.com/playproject-io/datdot-ui/issues/23) component the todo list of sub components is missing
* in the [`work screen` issues](https://github.com/playproject-io/datdot-ui/issues/24) there are some additional todos in that list from the past that might need some groupiing too


also regarding **"implementation"** in general - if the specific issues dont exist yet, maybe we can just add a regular `text todo` instead of an `todo issue link` to the components todo list or the parents subcomponents todos, etc..., **but include a link to the components repository where the implementation already started** :-)

**Comment by ninabreznik** [comment]
[datdot ui worklog: design and implementation phase issues and todos Mar 27, 2022](https://youtu.be/5tYToLbWN2A)

Issue: https://github.com/playproject-io/datdot-ui/issues/123 (cleanup issues and todos/structure issues and subissues into components + phases issues (2/3))

Results: 
- [wireframe-datdot-webapp](]https://github.com/playproject-io/datdot-ui/issues/125)
- [implement-datdot-webapp](]https://github.com/playproject-io/datdot-ui/issues/168)

**Comment by serapath** [comment]
**feedback `2022.03.27`**

issue 1 includes "styleguide" (which is basically a seperate app) and "components" under *Design phase*, but i think those are not just "design" so they should be standalone main todos instead. Also the design and implementation of the datdot-webapp should be linked in the datdot-webapp component issue anyway, which means the root issue could literally just list the main apps we make and maybe unrelated additional project issues, like the cleanup, so the issue would only contain:

1. datdot-styleguide
2. datdot-webapp 
3. cleanup issue (as an additional issue)

**Comment by ninabreznik** [comment]
Issue: #123

Results:
#9 
#169

**Comment by serapath** [comment]
**feedback `2022.03.29`**

1. the overview issue over all components is nice, because we can quickly see everything but it also means it needs to be kept up to date and maintained and we should not forget that, otherwise it becomes useless sadly or at least misleading.

2. The "general UI components" only exist because we are in an unfinished state, where the implementation has started but tdid not yet progress to implement our app specific components and for example one of the "general UI components" is actually called `plan summary` so in fact those UI elements are also made by us in datdot and not by somebody else and they are just the most atomic components but those atomic components will all neatnessly fit into the most basic app specific components which are composed of those basic ones and then the more complex ones are composed of those ...there is no clear cut

`ISSUE` to be more meaningful, there needs to be some "planning" where we specify the most atomic datdot specific components (e.g. `plan -add/edit - step: publish` or any other) and define or link those "general UI components" which are used to make it. If we do that for all of our datdot components, then the "general UI components" will go away and they will all be part of the one and only component tree.
  * **actually** you already did that for example in the `user - dashboard` where you linked all the "general UI components" used in thise dashboard
  * you mention in `user dashboard` #56 the "web app sub components" (which are not listed yet) ...but our self made UI components like datdot-button is nothing else than yet another "web app sub component" and to be honest that any other app out there will actualyl re-use our button is very unlikely

3. the same is true for `user-add-new-account`
  * which has a few "web app sub components" listed
  * and one of them is `user - add new account - option` which has again "web app sub components" listed
    * **BUT:** it doesnt have any other sub components then our custom made datdot button, icon, etc.. components

:+1:  its a nice summary otherwise :-) very cool.

**Comment by ninabreznik** [comment]
> **feedback `2022.03.29`**
> 
> 1. the overview issue over all components is nice, because we can quickly see everything but it also means it needs to be kept up to date and maintained and we should not forget that, otherwise it becomes useless sadly or at least misleading.
> 2. The "general UI components" only exist because we are in an unfinished state, where the implementation has started but tdid not yet progress to implement our app specific components and for example one of the "general UI components" is actually called `plan summary` so in fact those UI elements are also made by us in datdot and not by somebody else and they are just the most atomic components but those atomic components will all neatnessly fit into the most basic app specific components which are composed of those basic ones and then the more complex ones are composed of those ...there is no clear cut
> 
> `ISSUE` to be more meaningful, there needs to be some "planning" where we specify the most atomic datdot specific components (e.g. `plan -add/edit - step: publish` or any other) and define or link those "general UI components" which are used to make it. If we do that for all of our datdot components, then the "general UI components" will go away and they will all be part of the one and only component tree.
> 
> * **actually** you already did that for example in the `user - dashboard` where you linked all the "general UI components" used in thise dashboard
> * you mention in `user dashboard` [user - dashboard #56](https://github.com/playproject-io/datdot-ui/issues/56) the "web app sub components" (which are not listed yet) ...but our self made UI components like datdot-button is nothing else than yet another "web app sub component" and to be honest that any other app out there will actualyl re-use our button is very unlikely
> 
> 3. the same is true for `user-add-new-account`
> 
> * which has a few "web app sub components" listed
> * and one of them is `user - add new account - option` which has again "web app sub components" listed
>   
>   * **BUT:** it doesnt have any other sub components then our custom made datdot button, icon, etc.. components
> 
> +1 its a nice summary otherwise :-) very cool.

I agree, the distinction between webapp components and so called ui elementes is not very clear. So far in my head I imagine webapp components as very custom components, built out of general ui elements. And the general ui elements I see as building blocks for any app we will build with Playproject so maybe they will eventually move from datdotorg repo into playproject ui elements or (datdot ui repo) while the custom components don;t need to live as stand alone modules, but can live inside of the webapp repo.

**Comment by serapath** [comment]
**feedback `2022.04.01`**

great work and thx for the cleanup :-)

1. one thing you didn't tell in the worklog and i i think it might be missing is to tkae her notes, which i think represent non-issue textual todos of which some already have a :heavy_check_mark: green checkmark indicating they are done and adding all of them as todos to the list in their corresponding issues.
  * https://github.com/playproject-io/datdot-ui/issues/119

2. also the same issue https://github.com/playproject-io/datdot-ui/issues/119 has comments
  * each comment describes some notes about what fiona already did and when we come to the corresponding component issue to continue implementation, i think it could help if we would copy those work notes per component into the **info section** of that issue
    * https://github.com/playproject-io/datdot-ui/issues/119#issuecomment-885779061
     * https://github.com/playproject-io/datdot-ui/issues/119#issuecomment-894799125

but yes, looks like we basically have it now :-) awesome

**Comment by ninabreznik** [comment]
**[worklog `2022.03.31`](https://youtu.be/DVaF8GMnBrA)**

* Results:
  * #215 Updated issue and todos with comments from #119
  * issue closed, tasks done https://github.com/playproject-io/datdot-ui/issues/123#issue-1180242502
  * #232 Overview issue (move 2 items from cleanup issue over here)
