### ISSUE TITLE
components's api

### ISSUE THREAD

**Issue by ninabreznik** [datdotorg/datdot-ui#234]
## `@todo`

- [ ] first cleanup each component (start with the components without dependencies and moving up)
  - [ ] create a version tag (0.0.1)
  - [ ] move terminal/logs to dev dependencies
  - [ ] update package.json (new path  for the dependencies)

NEXT
- [ ] analyze and document each component
- [ ] take each component and redefine messages & statuses (update documentaiton)
- [ ] make new demo-maker component
  - [ ] text box with title, description and execute button
  - [ ] container element with the ui component you are demoing

**Comment by ninabreznik** [comment]
[worklog]

Results:
- https://github.com/datdot-ui/button/tree/v0.0.1-alpha
- https://github.com/datdot-ui/datepicker/tree/v0.0.1-alpha
- https://github.com/datdot-ui/dropdown/tree/v0.0.1-alpha
- https://github.com/datdot-ui/filter/tree/v0.0.1-alpha
- https://github.com/datdot-ui/icon/tree/v0.0.1-alpha
- https://github.com/datdot-ui/input/tree/v0.0.1-alpha
- https://github.com/datdot-ui/list/tree/v0.0.1-alpha
- https://github.com/datdot-ui/domlog/tree/v0.0.1-alpha
- https://github.com/datdot-ui/logs/tree/v0.0.1-alpha
- https://github.com/datdot-ui/range-slider/tree/v0.0.1-alpha
