### ISSUE TITLE
[UI] Filter

### ISSUE THREAD

**Issue by fionataeyang** [datdotorg/datdot-ui#53]
## `@todo`
* [x] implement first iteration of component
  * [x] create repository
  * [x] set up local dev environment with **pnpm**
    * [x] pnpm link the modules locally
      * [x] `pnpm link --global` (to make them available)
      * [x] `pnpm link --global <./package.json#name>`
  * `@output` :package: [`repository`](https://github.com/datdot-ui/filter/tree/8f27dfc1c715cd739875086b0d526b63e59da184)
* [x] refactor component for filter and its dependencies and tag with `v0.0.0-prealpha`
  * `@output` :package: [`repository`](https://github.com/datdot-ui/filter/tree/8f27dfc1c715cd739875086b0d526b63e59da184)
  * [x] refactor very old commit with domlog and old button/icon to use versions
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * `@output` :package: [`v0.0.0-prealpha`](https://github.com/datdot-ui/filter/tree/v0.0.0-prealpha)
* [x] refactor component latest commit with new comm protocol and tag with `v0.0.1-alpha`
  * `@input` :package: [`v0.0.0-prealpha`](https://github.com/datdot-ui/filter/tree/v0.0.0-prealpha)
  * [x] refactor latest commit with latest terminal/log to use versions
  * [x] refactor communication protocol to use latest message standard
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * [x] update github page links
  * [x] build new bundle.js to include changes in demo page
  * `@output` :package: [`v0.0.1-alpha`](https://github.com/datdot-ui/filter/tree/v0.0.1-alpha)
* [ ] refactor component latest commit with new comm protocol and tag with v0.0.3-alpha
  * `@input` :package: [`v0.0.2-alpha`](https://github.com/datdot-ui/checkbox/tree/v0.0.2-alpha)
  * [ ] set up github page using demo maker component dev dependency
  * `@output` :question: `repository#v0.0.3-alpha`
* [ ] implement next component version `v0.0.4-alpha`
  * `@input` :package: [`v0.0.3-alpha`](https://github.com/datdot-ui/filter/tree/v0.0.3-alpha)
  * [ ] fix bugs & add features for v0.0.4
    * [x] Data: Option list(Available, Not available, Hypercore, Hyperdrive, Cabal)
    * [x] Add CSS style
    * [x] Import #3 datdot-ui-button
    * [x] Import ui-domlog
    * [x] Toggle check function
    * [x] Get result from filter option
    * [ ] Testing string compare on Safari (with @serapath) 
    * [ ] Refactor codes(protocol, receive, recipients)
    * [ ] refactor all `messages` and `status` and update documentation
  * [ ] set up github page using demo maker component dev dependency
  * [ ] document component api in readme or whatever needs to show in the readme
    * [ ] document apis for each screen and return available actions
      * `@input` :question: `wireframes action bars`
  * [ ] document component api in readme
    * [ ] list all `opts`
    * [ ] list all `roles`
    * [ ] list all `incoming message types`
    * [ ] list all `outgoing message types`
    * [ ] list all possible `status` the component instance can be in
  * [ ] install latest dev dependencies
    * [ ] budo
    * [ ] browserify
    * [ ] datdot-terminal
  * [ ] install latest specific version of dependencies
    * [ ] #3
  * [ ] update github page links
  * [ ] build new bundle.js to include changes in demo page
  * [ ] update package.json (new path for the dependencies)
  * `@output` :question: `v0.0.4-alpha`

---

## `@info`

THIS ELEMENT has been merged with the dropdown #71

```js
// datdot-ui-filter
require('datdot-ui-button')
```

### Repo :open_file_folder:
https://github.com/datdot-ui/filter 

### for PLANS
![image](https://user-images.githubusercontent.com/9526525/116712086-1132ce00-aa06-11eb-8841-e629e2c2165a.png)
Filter by
1. Name
2. Swarm
3. Feeds
4. Chunks
5. Price
6. Start date
7. End date
8. Data size
9. Location

# Filter option
![image](https://user-images.githubusercontent.com/9526525/103095744-ac70fc80-463c-11eb-9cf7-5f29e95fdfbe.png)![image](https://user-images.githubusercontent.com/9526525/103058674-d3e4ac80-45dd-11eb-9ecd-6c4190977617.png)![image](https://user-images.githubusercontent.com/9526525/103095719-9a8f5980-463c-11eb-8e4a-a65761fb36a0.png)

### Repo
https://github.com/datdotorg/datdot-ui-filter-option 

### Important issue
1. string compare failed in Safari
From data entry 
```js
let optionList = { unchecked: [], checked: ['Available', 'Not available', 'Hypercore', 'Hyperdrive', 'Cabal']}
```
Option button
```
const option = filterOption({page, flow, name: 'filter-option', data: optionList.checked}, optionProtocol('filter-option'))
```

```js
function optionProtocol (name) {
....
....
// get type 'unchecked' or 'checked' to check from and currentValue are equality.
if (type === 'unchecked') {
      // handle chekced status
      const result = optionList.checked.reduce( (acc, currentValue) => {
      if (from === currentValue) {
            const index = optionList.checked.indexOf(from)
            optionList.unchecked.push(from)
            optionList.checked.splice(index, 1)
      }
      acc = optionList.checked
      return acc
}, [])

if (type === 'checked') {
      // handle unchecked status
      const result = optionList.unchecked.reduce( (acc, currentValue) => {
      if (from === currentValue) {
            const index = optionList.unchecked.indexOf(from)
            optionList.checked.push(from)
            optionList.unchecked.splice(index, 1)
      }
      acc = optionList.checked
      return acc
}, [])
```

This code line is an issue to cause compare failed on Safari
```js
from === currentValue
```
even change ```===``` to ```==``` is failed too
```js
option == from
```
Chrome
![image](https://user-images.githubusercontent.com/9526525/103059512-4c4c6d00-45e0-11eb-9360-980fa7e79c82.png)

Safari
![image](https://user-images.githubusercontent.com/9526525/103059467-2aeb8100-45e0-11eb-80a0-6d1feee707a0.png)

#### Chrome result
![image](https://user-images.githubusercontent.com/9526525/103057926-d34b1680-45db-11eb-9106-9c0b79c0c2d1.png)
#### Safari result
![image](https://user-images.githubusercontent.com/9526525/103057919-cc240880-45db-11eb-8275-9ede53fe8d0f.png) ![image](https://user-images.githubusercontent.com/9526525/103057903-c4fcfa80-45db-11eb-99d0-06b045ea42fd.png)

Even I do console.log(typeof from, typeof currentValue)
This is what've I got
![image](https://user-images.githubusercontent.com/9526525/103058000-fd9cd400-45db-11eb-990e-ab1502e8cf20.png)

I've tried many ways with different pattern in JavaScript
```js
let optionList = { unchecked: [], checked: ['Available', 'Not available', 'Hypercore', 'Hyperdrive', 'Cabal']}
optionList.checked.findIndex( option => option === from ) // -1
optionList.splice( optionList.checked.indexOf(from), 1) // it is worked fine in Codepen.io 
```

## Solution
1.  Refactor entry data structure 
```js
const data = [
        {id: 1, status: "Available", active: true}, 
        {id: 2, status: "Not available", active: false}, 
        {id: 3, status: "Hypercore", active: true},
        {id: 4, status: "Hyperdrive", active: false},
        {id: 5, status: "Cabal", active: true}
    ]
```
2. Use id to compare with button's index
```
src/index.js
```
```js
// get lits
    optionListRender(data).then( buttons => {
        buttons.map( (item, i) => { 
            const li = bel`<li>${item}</li>`
            // need to set an id to button for toggle using, because Safari cannot compare body or from (string issue)
            item.setAttribute('id', i+1)
            optionList.append(li) 
        })
        return buttons
    })
```
3. make new function to toggle check
![image](https://user-images.githubusercontent.com/9526525/103058659-c2030980-45dd-11eb-9829-9abaf71554e3.png)

```
demo/demo.js
```
```js
function actionToggleCheck (message) {
...
...
      data.map( item => { 
            // * better to use return item for add more conditions
            if (item.id === body ) item.active = !item.active 
            return item
        })
```

It is still failed when I refactored the data structure and test again via ```item.status``` and ```body```
![image](https://user-images.githubusercontent.com/9526525/103058746-15755780-45de-11eb-878d-9cefafe5eb12.png)
```typeof item.status``` and ```typeof body``` are all string, somehow it is failed to compare string in Safari.
```item.status.localeCompare(body)``` is also return ```-1```, only ```0``` is matched

---
### Conclusion
Use regex.test(string) to compare from existed array instead of comparing string by from to fix issue on Safari
```js
let options = optionList.map( item => { 
    // * better to use return item for add more conditions
    if (item.id === body ) item.active = !item.active
    if (/^Available/.test(item.status) && item.active ) on = online(data)
    if (/^Not available/.test(item.status) && item.active ) off = offline(data)
    return item
}).map( item => {
    if (/core/i.test(item.status) && item.active) {
            let arr = data.filter( obj => /core/i.test(obj.type))
            return result.push(...arr)
    }
    if (/drive/i.test(item.status) && item.active) {
            let arr = data.filter( obj => /drive/i.test(obj.type)) 
            return result.push(...arr)
    }
    if (/cabal/i.test(item.status) && item.active) {
            let arr = data.filter( obj => /cabal/i.test(obj.type))
            return result.push(...arr)
    }
    return item
})
```

**Comment by fionataeyang** [comment]
```js
// datdot-ui-filter
require('datdot-ui-button')
```

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol

### Results:
**v0.0.1-alpha** (using new comm proto)
- https://github.com/datdot-ui/filter/tree/v0.0.1-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.1-alpha`
  - https://github.com/datdot-ui/filter/tree/v0.0.1-alpha
- `v0.0.0-prealpha`
    - https://github.com/datdot-ui/filter/tree/v0.0.0-prealpha

**Comment by ninabreznik** [comment]
Merged with #71
