### ISSUE TITLE
[UI] Input

### ISSUE THREAD

**Issue by fionataeyang** [datdotorg/datdot-ui#77]
## `@todo`
* [x] implement first iteration of component
  * [x] create repository
  * [x] set up local dev environment with **pnpm**
    * [x] pnpm link the modules locally
      * [x] `pnpm link --global` (to make them available)
      * [x] `pnpm link --global <./package.json#name>`
  * `@output` :package: [`repository`](https://github.com/datdot-ui/input/tree/652350a89916bd5f18fdc044f2d7bcc12a203cb8)
* [x] refactor component for last Fiona's commit and tag it with `v0.0.0-alpha`
  * `@input` :package: [`repository`](https://github.com/datdot-ui/input/tree/652350a89916bd5f18fdc044f2d7bcc12a203cb8)
  * [x] refactor commit with latest terminal/log to use versions
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * [ ] `@output` :package: [`v0.0.0-alpha`](https://github.com/datdot-ui/input/tree/v0.0.0-alpha)
* [x] refactor component latest commit with new comm protocol and tag with `v0.0.1-alpha`
  * [ ] `@input` :package: [`v0.0.0-alpha`](https://github.com/datdot-ui/input/tree/v0.0.0-alpha)
  * [x] refactor latest commit with latest terminal/log to use versions
  * [x] refactor communication protocol to use latest message standard
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * [x] update github page links
  * [x] build new bundle.js to include changes in demo page
  * [x] support theme
  * `@output` :package: [`v0.0.1-alpha`](https://github.com/datdot-ui/input/tree/v0.0.1-alpha)
      * next #242
      * next #243
      * next #244
      * next #11

---

### Repo :open_file_folder:
https://github.com/datdotorg/datdot-ui-input

### Notes 
(by @fionataeyang)
- It is a bit complicated widget for many types of input, like text, number, textarea, slide range, checkbox, radio 
- Text input is part of form when it needs to fill field information like create new account form https://github.com/playproject-io/datdot-ui/issues/32 , transfer https://github.com/playproject-io/datdot-ui/issues/41 , import account form https://github.com/playproject-io/datdot-ui/issues/33, edit account https://github.com/playproject-io/datdot-ui/issues/40, search https://github.com/playproject-io/datdot-ui/issues/99, plan name #103
- Number input is part of form when it needs to fill field information like transfer https://github.com/playproject-io/datdot-ui/issues/41, and also it needs to support increment and decrement that is something haven't thought yet when did UI design.
And also have to support calculation for big number which is we don't use any 3rd dependence to help calculation with big number, like balance, transfer and transaction would be using it.
Thus, this is big matter to whole app that user and our platform all care.
- Checkbox is part of form that it is using on set time, set repeat, custom days. And also it has to support custom checkbox via SVG icon and theme
- Radio is part of form. It can support custom radio via SVG icon and theme
- Should we use a custom element via div instead of text area? We've been used it on smarcontract.codes for search code snippets. Or let user can choose use native text area or custom area?
- Password is very important with account security. No plan yet.

#### Text
![image](https://user-images.githubusercontent.com/9526525/117848640-102b5780-b2b6-11eb-8dce-3bc8d9870cae.png)
![image](https://user-images.githubusercontent.com/9526525/117848720-233e2780-b2b6-11eb-8871-d6fd2df77084.png)
![image](https://user-images.githubusercontent.com/9526525/117848889-541e5c80-b2b6-11eb-893c-ab942c56a1e2.png)
![image](https://user-images.githubusercontent.com/9526525/117848906-597ba700-b2b6-11eb-846f-953e76c631e2.png)

#### Textarea

![image](https://user-images.githubusercontent.com/9526525/117849872-5339fa80-b2b7-11eb-9eee-ff63151c4cbd.png)

---
#### Number
![image](https://user-images.githubusercontent.com/9526525/117848685-1a4d5600-b2b6-11eb-9029-c0b5ffe465dd.png)

##### SET repeat

**Unchecked**
![image](https://user-images.githubusercontent.com/9526525/117007689-86f7ac00-ad1c-11eb-94e6-c000ae47e4d9.png)

**Checked**
By Everyday
![image](https://user-images.githubusercontent.com/9526525/117008320-2ddc4800-ad1d-11eb-8e91-291bf279ba53.png)

By Weekday
![image](https://user-images.githubusercontent.com/9526525/117008225-14d39700-ad1d-11eb-8f9b-ec95ff0d35df.png)

By Every week
![image](https://user-images.githubusercontent.com/9526525/117008564-73007a00-ad1d-11eb-89ba-c3ebd2acd081.png)

By Every first
![image](https://user-images.githubusercontent.com/9526525/117008647-86abe080-ad1d-11eb-9638-88a9758a642a.png)

##### SET time 

**Unchecked**
![image](https://user-images.githubusercontent.com/9526525/117846532-1caeb080-b2b4-11eb-98ab-93db023e8673.png)

**Checked**
![image](https://user-images.githubusercontent.com/9526525/117846520-191b2980-b2b4-11eb-89dd-b4316c4fd29d.png)

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol

### Results:
**v0.0.1-alpha** (using new comm proto)
- https://github.com/datdot-ui/input/tree/v0.0.1-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.1-alpha`
  - https://github.com/datdot-ui/input/tree/v0.0.1-alpha
-  `v0.0.0-alpha` 
    - https://github.com/datdot-ui/input/tree/v0.0.0-alpha
- updated readme
    - https://github.com/datdot-ui/input

**Comment by ninabreznik** [comment]
[[datdot ui worklog] working on v0.0.2-alpha Apr 18, 2022 ](https://youtu.be/bjKH1EkFNFI)

**results:**

- `v0.0.2`
  - https://github.com/datdot-ui/input-number/tree/v0.0.2-alpha
  - https://github.com/datdot-ui/input-text/tree/v0.0.2-alpha
  - https://github.com/datdot-ui/checkbox/tree/v0.0.2-alpha
