### ISSUE TITLE
[UI] Title

### ISSUE THREAD

**Issue by fionataeyang** [datdotorg/datdot-ui#84]
## `@todo`
* [x] implement first iteration of component
  * [x] create repository
  * [x] set up local dev environment with **pnpm**
    * [x] pnpm link the modules locally
      * [x] `pnpm link --global` (to make them available)
      * [x] `pnpm link --global <./package.json#name>`
  * `@output` :package: [`repository`](https://github.com/datdot-ui/title/tree/aa01b13d07502eccdd376c77a4856bcef2445c39)
* [x] refactor component for last Fiona's commit and tag it with `v0.0.0-alpha`
  * `@input` :package: [`repository`](https://github.com/datdot-ui/title/tree/aa01b13d07502eccdd376c77a4856bcef2445c39)
  * [x] refactor commit with latest terminal/log to use versions
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * `@output` :package: [`v0.0.0-alpha`](https://github.com/datdot-ui/title/tree/v0.0.0-alpha)
* [x] refactor component latest commit with new comm protocol and tag with `v0.0.1-alpha`
  * `@input` :package: [`v0.0.0-alpha`](https://github.com/datdot-ui/title/tree/v0.0.0-alpha)
  * [x] refactor latest commit with latest terminal/log to use versions
  * [x] refactor communication protocol to use latest message standard
  * [x] move terminal/logs to dev dependencies
  * [x] rebase main branch on top of taged version
  * [x] update package.json (new path for the dependencies)
  * [x] update github page links
  * [x] build new bundle.js to include changes in demo page
  * `@output` :package: [`v0.0.1-alpha`](https://github.com/datdot-ui/title/tree/v0.0.1-alpha)
* [x] implement next component version `v0.0.2-alpha`
  * `@input` :package: [`v0.0.1-alpha`](https://github.com/datdot-ui/title/tree/v0.0.1-alpha)
  * [x] fix bugs & add features for v0.0.2
    * [x] Refactor codes(protocol, receive, recipients)
    * [x] refactor all `messages` and `status` and update documentation
  * [x] document component api in readme
    * [x] list all `opts`
    * [x] list all `roles`
    * [x] list all `incoming message types`
    * [x] list all `outgoing message types`
    * [x] list all possible `status` the component instance can be in
    * `@output` :package: [README.md](https://github.com/datdot-ui/title/blob/82e5638c86589396e323c006ebb6ebad67700af2/README.md)
  * [x] install latest dev dependencies
    * [x] budo
    * [x] browserify
    * [x] datdot-terminal
  * [x] update github page links
  * [x] build new bundle.js to include changes in demo page
  * [x] update package.json (new path for the dependencies)
  * `@output` :package: [`repository#v0.0.2-alpha`](https://github.com/datdot-ui/title/tree/v0.0.2-alpha)
* [ ] refactor component latest commit with new comm protocol and tag with `v0.0.3-alpha`
  * `@input` :package: [`v0.0.2-alpha`](https://github.com/datdot-ui/title/tree/v0.0.2-alpha)
    * [ ] set up github page using demo maker component dev dependency
    * [ ] add ref to messages 
    * [ ] document component api in readme or whatever needs to show in the readme
      * [ ] document apis for each screen and return available actions
  * `@output` :package: [`v0.0.3-alpha`] :question:
---

### Repo :open_file_folder:
https://github.com/datdot-ui/title/

### First text or top of head
![image](https://user-images.githubusercontent.com/9526525/117975116-e9762b00-b360-11eb-8599-13eee5cbc962.png)

![image](https://user-images.githubusercontent.com/9526525/117975157-f4c95680-b360-11eb-8319-54b9c3d03c97.png)

![image](https://user-images.githubusercontent.com/9526525/117975176-f8f57400-b360-11eb-95ce-4b0ee7279f8d.png)

# Sub title
Second large size of title

![image](https://user-images.githubusercontent.com/9526525/117975590-67d2cd00-b361-11eb-95da-55877bc7f1a2.png)

![image](https://user-images.githubusercontent.com/9526525/117975691-83d66e80-b361-11eb-996f-f94b19a17451.png)

# label

![image](https://user-images.githubusercontent.com/9526525/117849361-d149d180-b2b6-11eb-8f80-d1a038ca6dde.png)

![image](https://user-images.githubusercontent.com/9526525/117849347-cee77780-b2b6-11eb-8677-9cae7d5c23ae.png)

![image](https://user-images.githubusercontent.com/9526525/117849311-c727d300-b2b6-11eb-8a2a-cd482f1e9bc8.png)

![image](https://user-images.githubusercontent.com/9526525/117849483-f1799080-b2b6-11eb-9fa5-a638277ec297.png)

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.07` - locking UI elements**](https://youtu.be/X8wpMNnAW2E) 

Notes:
- v.0.0.1-alpha: ui elements, updated to use new comm protocol

### Results:
**v0.0.1-alpha** (using new comm proto)
- https://github.com/datdot-ui/title/tree/v0.0.1-alpha

**Comment by serapath** [comment]
> @ninabreznik 
> [**worklog `2022.04.12` - versioning and documenting components**](https://youtu.be/gCKEtJ2eG8o)

**results:**

- `v0.0.1-alpha`
  - https://github.com/datdot-ui/title/tree/v0.0.1-alpha
-  `v0.0.0-alpha` 
    - https://github.com/datdot-ui/title/tree/v0.0.0-alpha
- updated readme
    - https://github.com/datdot-ui/title/

**Comment by ninabreznik** [comment]
[[datdot ui worklog] working on v0.0.2-alpha Apr 18, 2022 ]()

**results:**

- `v0.0.2`
  - https://github.com/datdot-ui/title/tree/v0.0.2-alpha
